
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE 0
#define PARTNER_STEVEN 1
#define PARTNER_WALLY 2
#define PARTNER_BRENDAN_MUDKIP 3
#define PARTNER_BRENDAN_TREECKO 4
#define PARTNER_BRENDAN_TORCHIC 5
#define PARTNER_MAY_MUDKIP 6
#define PARTNER_MAY_TREECKO 7
#define PARTNER_MAY_TORCHIC 8
#define PARTNER_COUNT 9

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
